apiVersion: v1
kind: Namespace
metadata:
  name: rbac-demo
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubectl
  namespace: rbac-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubectl
  template:
    metadata:
      labels:
        app: kubectl
    spec:
    #  serviceAccountName: kubectl-pod
      containers:
        - name: kubectl
          image: bitnami/kubectl
          command: ["sh", "-c", "sleep infinity"]
          resources: {}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: rbac-demo
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-can-read-pods-in-namespace
  namespace: rbac-demo
subjects:
  - kind: ServiceAccount
    name: kubectl-pod
    namespace: rbac-demo
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-pod
  namespace: rbac-demo
