apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-can-read-pods-in-namespace
  namespace: rbac-demo
subjects:
  - kind: ServiceAccount
    name: kubectl-pod
    namespace: rbac-demo
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
