apiVersion: v1
kind: Namespace
metadata:
  name: pod-demo

---

apiVersion: v1
kind: Pod
metadata:
  name: k8session-pod-demo
  namespace: pod-demo
spec:
  containers:
    - name: dotnet-webapi
      image: arunap2509/k8session-poddemo
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      resources: {}  # Empty resources block to avoid validation error
  restartPolicy: Always
  