apiVersion: v1
kind: Namespace
metadata:
  name: daemonset-demo

---
apiVersion: v1
kind: DaemonSet
metadata:
  name: fluentd-elasticsearch
  namespace: daemonset-demo
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      containers:
      - name: fluentd-elasticsearch
        image: quay.io/fluent_elasticsearch/fluentd-elasticsearch:v2.5.0
