apiVersion: v1
kind: Namespace
metadata:
  name: job-demo
---

apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
  namespace: job-demo
spec:
  template:
    spec:
      containers:
        - name: job-demo-console-app
          image: arunap2509/k8session-jobdemo:latest
          # args: ["simulateError"]
      restartPolicy: OnFailure
  completions: 2
  parallelism: 2
  backoffLimit: 6
  ttlSecondsAfterFinished: 5
  completionMode: Indexed # Only valid with parallelism >1 and with a completions value.
      # Sets zero-based JOB_COMPLETION_INDEX environment variable in the container.
  
---
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: periodic-task
#   namespace: job-demo
# spec:
#   schedule: "0 */6 * * *"  # Every 6 hours
#   concurrencyPolicy: "Forbid" # allow, replace
#   successfulJobsHistoryLimit: 2
#   failedJobsHistoryLimit: 2
#   jobTemplate:
#     spec:
#       parallelism: 2        # Max 2 jobs run in parallel
#       completions: 3        # Total of 3 jobs
#       completionMode: Indexed  # Enables indexed jobs
#       template:
#         spec:
#           containers:
#             - name: job-demo-console-app
#               image: arunap2509/k8session-jobdemo:latest
# #              args: ["simulateError"]
#           restartPolicy: OnFailure
