apiVersion: v1
kind: Namespace
metadata:
  name: config-demo

---
apiVersion: v1
kind: Service
metadata:
  name: k8session-helper-service
  namespace: config-demo
spec:
  selector:
    app: dotnet-helper-webapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30015
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8session-helper-api
  namespace: config-demo
  labels:
    app: dotnet-helper-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-helper-webapi
  template:
    metadata:
      labels:
        app: dotnet-helper-webapi
    spec:
      containers:
        - name: dotnet-helper-webapi
          image: arunap2509/k8session-configmaps:latest
          envFrom:
            - configMapRef:
                name: helper-api-config
          env:
           - name: JOB_ENV_VARIABLE
             valueFrom:
               configMapKeyRef:
                 name: helper-api-config
                 key: Job
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: helper-api-config
  namespace: config-demo
data:
  Name: 'John'
  Job: 'Engineer'
